# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f88c7a016bfed3a414db46a85baea35b5c4fddec616e975add6b7f9497012742fe6bf44d7f8ccb1bfcec98792d30fceff38fc854ac61ceb7aa3549246010165

test:
  secret_key_base: 8f9d9a3a210218f54ca4ec722805d95e5d93b73a9a2b68fb66fc801968931f9487ec227f6ae0a941169a777605abd4237e06df592c91387afc7a033d8becbb85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
